### ISSUE TITLE
'%' not encoding all the times

### ISSUE THREAD

**Issue by kishore-indraganti** [pillarjs/encodeurl#3]
```
const encodeurl = require('encodeurl');


console.log(encodeurl('%KF')); //%25KF
console.log(encodeurl('%EB')); //%EB
```

why this behavriour?

**Comment by dougwilson** [comment]
It is explained in the README:

> This function will not encode the "%" character unless it is not part of a valid sequence (%20 will be left as-is, but %foo will be encoded as %25foo).
